# Sample .travis.yml for R projects.
#
# See the r-travis repo and its wiki
#   https://github.com/craigcitro/r-travis/wiki
#   https://github.com/eddelbuettel/r-travis/
sudo: false

language: r
cache: packages

os:
  - linux
  - osx

osx_image: xcode7.1

r:
  - release

notifications:
  email:
    on_success: change
    on_failure: change
