// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/ropencc.h"
#include <Rcpp.h>

using namespace Rcpp;

// converter_create
XPtr<ConverterPtr> converter_create(CharacterVector file_);
RcppExport SEXP ropencc_converter_create(SEXP file_SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type file_(file_SEXP);
    __result = Rcpp::wrap(converter_create(file_));
    return __result;
END_RCPP
}
// extract_create
XPtr<PhraseExtract> extract_create();
RcppExport SEXP ropencc_extract_create() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(extract_create());
    return __result;
END_RCPP
}
// extract_set
SEXP extract_set(XPtr<PhraseExtract> ptr, int WordMaxLength, int PrefixSetLength, int SuffixSetLength);
RcppExport SEXP ropencc_extract_set(SEXP ptrSEXP, SEXP WordMaxLengthSEXP, SEXP PrefixSetLengthSEXP, SEXP SuffixSetLengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< XPtr<PhraseExtract> >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< int >::type WordMaxLength(WordMaxLengthSEXP);
    Rcpp::traits::input_parameter< int >::type PrefixSetLength(PrefixSetLengthSEXP);
    Rcpp::traits::input_parameter< int >::type SuffixSetLength(SuffixSetLengthSEXP);
    __result = Rcpp::wrap(extract_set(ptr, WordMaxLength, PrefixSetLength, SuffixSetLength));
    return __result;
END_RCPP
}
// extract
List extract(XPtr<PhraseExtract> extractor, CharacterVector input_);
RcppExport SEXP ropencc_extract(SEXP extractorSEXP, SEXP input_SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< XPtr<PhraseExtract> >::type extractor(extractorSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type input_(input_SEXP);
    __result = Rcpp::wrap(extract(extractor, input_));
    return __result;
END_RCPP
}
// convert
CharacterVector convert(XPtr<ConverterPtr> ptr, CharacterVector input_);
RcppExport SEXP ropencc_convert(SEXP ptrSEXP, SEXP input_SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< XPtr<ConverterPtr> >::type ptr(ptrSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type input_(input_SEXP);
    __result = Rcpp::wrap(convert(ptr, input_));
    return __result;
END_RCPP
}
// convert_dict
SEXP convert_dict(CharacterVector input_, CharacterVector output_, CharacterVector from, CharacterVector to);
RcppExport SEXP ropencc_convert_dict(SEXP input_SEXP, SEXP output_SEXP, SEXP fromSEXP, SEXP toSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type input_(input_SEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type output_(output_SEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type from(fromSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type to(toSEXP);
    __result = Rcpp::wrap(convert_dict(input_, output_, from, to));
    return __result;
END_RCPP
}
