# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

converter_create <- function(file_) {
    .Call('ropencc_converter_create', PACKAGE = 'ropencc', file_)
}

extract_create <- function() {
    .Call('ropencc_extract_create', PACKAGE = 'ropencc')
}

extract_set <- function(ptr, WordMaxLength, PrefixSetLength, SuffixSetLength) {
    .Call('ropencc_extract_set', PACKAGE = 'ropencc', ptr, WordMaxLength, PrefixSetLength, SuffixSetLength)
}

extract <- function(extractor, input_) {
    .Call('ropencc_extract', PACKAGE = 'ropencc', extractor, input_)
}

convert <- function(ptr, input_) {
    .Call('ropencc_convert', PACKAGE = 'ropencc', ptr, input_)
}

convert_dict <- function(input_, output_, from, to) {
    .Call('ropencc_convert_dict', PACKAGE = 'ropencc', input_, output_, from, to)
}

